[package]
name = "balloc"
version = "0.2.0"
authors = ["est31 <MTest31@outlook.com>"]
description = "Bounded allocation datastructures"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/balloc"
repository = "https://github.com/est31/balloc"
readme = "README.md"

[dependencies]
